# Write your MySQL query statement below
SELECT DISTINCT NUM AS CONSECUTIVENUMS
FROM (
    SELECT NUM,
    LEAD(NUM) OVER() as  NUM1,
    LAG(NUM) OVER() as NUM2
    FROM LOGS
) as t
WHERE NUM = NUM1 AND NUM = NUM2;