# Write your MySQL query statement below
SELECT E1.EMPLOYEE_ID
FROM EMPLOYEES AS E1
left JOIN EMPLOYEES AS E2
ON E1.MANAGER_ID = E2.EMPLOYEE_ID
WHERE E1.SALARY < 30000
AND E1.MANAGER_ID IS NOT NULL 
AND E2.EMPLOYEE_ID IS NULL
ORDER BY E1.EMPLOYEE_ID ASC;