-- # Write your MySQL query statement below
-- SELECT PRODUCT_ID, YEAR AS FIRST_YEAR, QUANTITY, PRICE
-- FROM SALES 
-- WHERE (PRODUCT_ID, YEAR) IN (
--     SELECT PRODUCT_ID, MIN(YEAR) AS FIRST_YEAR
--     FROM SALES
--     GROUP BY PRODUCT_ID
-- )

SELECT product_id, YEAR AS FIRST_YEAR, QUANTITY, PRICE
FROM 
(
    SELECT product_id, YEAR , QUANTITY, PRICE,
    Rank() OVER (PARTITION BY product_id ORDER BY YEAR ASC) AS RN
    FROM SALES
) AS T
WHERE RN = 1;


