# Write your MySQL query statement below
SELECT P.PRODUCT_NAME, SUM(O.UNIT) AS UNIT
FROM PRODUCTS AS P
JOIN ORDERS AS O
ON P.PRODUCT_ID = O.PRODUCT_ID
WHERE O.ORDER_DATE BETWEEN '2020-02-01' AND '2020-02-29'
GROUP BY P.PRODUCT_ID
HAVING SUM(O.UNIT) >= 100