# Write your MySQL query statement below
SELECT E1.REPORTS_TO AS EMPLOYEE_ID, E2.NAME, COUNT(E1.REPORTS_TO) AS REPORTS_COUNT, ROUND(AVG(E1.AGE),0) AS AVERAGE_AGE  
FROM EMPLOYEES AS E1
JOIN EMPLOYEES AS E2
ON E1.REPORTS_TO = E2.EMPLOYEE_ID
GROUP BY E1.REPORTS_TO
ORDER BY EMPLOYEE_ID ASC;