-- SELECT MAX(SALARY) AS SECONDHIGHESTSALARY
-- FROM EMPLOYEE
-- WHERE SALARY < (
--     SELECT MAX(SALARY) FROM
--     EMPLOYEE 
-- );

SELECT MAX(SALARY) AS SecondHighestSalary
FROM (
    SELECT salary,
           DENSE_RANK() OVER (ORDER BY salary DESC) AS rnk
    FROM Employee
) t
WHERE rnk = 2;
