SELECT DEPARTMENT, EMPLOYEE, SALARY
FROM (
    SELECT D.NAME AS DEPARTMENT, E.NAME AS EMPLOYEE, E.SALARY AS SALARY,
    DENSE_RANK() OVER(PARTITION BY D.NAME ORDER BY E.SALARY DESC) AS RNK
    FROM EMPLOYEE AS E
    JOIN DEPARTMENT AS D
    ON E.DEPARTMENTID = D.ID
    ) AS T
WHERE RNK <= 3;